astra_db:
   collection_name: "chatbot_ecommerce"

embedding_model:
   provider: "openai"
   model_name: "text-embedding-3-large"

retriever:
   top_k: 3


llm:
  provider: "openai"
  model_name: "gpt-4o-mini"